import os
import json
from services.dataset_service import DatasetService
from services.problem_detection_service import ProblemDetectionService
from repositories.experiment_repository import ExperimentRepository

class NotebookGeneratorService:
    @staticmethod
    def generate_notebook_dict(dataset_id: str, mode: str = "clean", user_id=None) -> dict:
        # 1. Load dataset details
        dataset = DatasetService.get_dataset_by_id(dataset_id, user_id=user_id)
        if not dataset:
            raise ValueError("Dataset not found")
        
        filename = dataset.get("filename", "dataset.csv")

        # 2. Load problem detection
        pd_info = ProblemDetectionService.detect_problem(dataset_id, user_id=user_id)
        target_column = pd_info.get("target_column")
        problem_type = pd_info.get("problem_type")
        classification_type = pd_info.get("classification_type")
        num_classes = pd_info.get("num_classes")

        # 3. Load latest experiment parameters
        experiments = ExperimentRepository.get_experiments_by_dataset(dataset_id, user_id=user_id)
        imputation_strategy = "median"
        outlier_threshold = "None"
        split_ratio = 0.8
        selected_models = []

        if experiments:
            latest = experiments[0]
            imputation_strategy = latest.get("imputation_strategy", "median")
            outlier_threshold = latest.get("outlier_threshold")
            if outlier_threshold is None:
                outlier_threshold = "None"
            split_ratio = latest.get("split_ratio", 0.8)
            selected_models = latest.get("selected_models", [])

        # Format selected models for python code
        selected_models_str = str(selected_models) if selected_models else "[]"

        cells = []

        # Helper to add markdown cell
        def add_markdown(source_lines):
            if mode == "learning":
                cells.append({
                    "cell_type": "markdown",
                    "metadata": {},
                    "source": [line + "\n" for line in source_lines]
                })

        # Helper to add code cell
        def add_code(source_lines):
            cells.append({
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [line + "\n" for line in source_lines]
            })

        # Top Title in Clean Mode
        if mode == "clean":
            cells.append({
                "cell_type": "markdown",
                "metadata": {},
                "source": [f"# Machine Learning Pipeline: {filename}\n"]
            })

        # Section 1: Dataset Loading
        add_markdown([
            "# 🚀 Machine Learning Code Export",
            "This notebook contains fully executable machine learning pipeline code generated by **Adaptive Data Science Assistant (ADSA)**.",
            "It replicates the exact data loading, preprocessing, EDA, model training, and evaluations performed on the platform.",
            "",
            "## Section 1: Dataset Loading",
            "Detects if executing in a Google Colab environment or local Jupyter runtime, providing file uploads in Colab."
        ])

        if mode == "clean":
            add_code([
                "# Load dataset",
                "import os",
                "import pandas as pd",
                "import io",
                "",
                "try:",
                "    import google.colab",
                "    in_colab = True",
                "except ImportError:",
                "    in_colab = False",
                "",
                "if in_colab:",
                "    from google.colab import files",
                "    uploaded = files.upload()",
                "    if uploaded:",
                "        filename = list(uploaded.keys())[0]",
                "        df = pd.read_csv(io.BytesIO(uploaded[filename]))",
                "    else:",
                "        raise ValueError('No file uploaded.')",
                "else:",
                f"    local_path = '{filename}'",
                "    if os.path.exists(local_path):",
                "        df = pd.read_csv(local_path)",
                "    else:",
                "        dataset_path = input('Enter path to dataset CSV: ')",
                "        df = pd.read_csv(dataset_path)"
            ])
        else:
            add_code([
                "import os",
                "import pandas as pd",
                "import io",
                "",
                "# Detect runtime environment",
                "try:",
                "    import google.colab",
                "    IN_COLAB = True",
                "except ImportError:",
                "    IN_COLAB = False",
                "",
                "if IN_COLAB:",
                "    print('Running in Google Colab. Please upload your dataset file.')",
                "    from google.colab import files",
                "    uploaded = files.upload()",
                "    if uploaded:",
                "        filename = list(uploaded.keys())[0]",
                "        df = pd.read_csv(io.BytesIO(uploaded[filename]))",
                "        print(f'Loaded dataset: {filename} with shape {df.shape}')",
                "    else:",
                "        raise ValueError('No file uploaded!')",
                "else:",
                f"    local_path = '{filename}'",
                "    if os.path.exists(local_path):",
                "        df = pd.read_csv(local_path)",
                "        print(f'Loaded local dataset: {local_path} with shape {df.shape}')",
                "    else:",
                "        print(f\"Local file '{local_path}' not found. Please place it in the same directory as this notebook.\")",
                "        dataset_path = input('Enter path to your dataset CSV file: ')",
                "        df = pd.read_csv(dataset_path)"
            ])

        # Section 2: Data Profiling
        add_markdown([
            "## Section 2: Data Profiling",
            "Prints shape, column names, general info, data types, and head of the dataset."
        ])

        if mode == "clean":
            add_code([
                "# Dataset overview",
                "print(df.shape)",
                "print(df.columns.tolist())",
                "df.info()",
                "display(df.head())"
            ])
        else:
            add_code([
                "print(f'Dataset Shape: {df.shape}')",
                "print('\\n--- Dataset Columns ---')",
                "print(df.columns.tolist())",
                "print('\\n--- Dataset Info ---')",
                "df.info()",
                "print('\\n--- Descriptive Statistics ---')",
                "display(df.describe(include='all'))",
                "print('\\n--- First 5 Rows ---')",
                "display(df.head())"
            ])

        # Section 3: Missing Value Handling & Outlier Clipping
        add_markdown([
            "## Section 3: Missing Value Handling & Outlier Clipping",
            f"Applies outlier clipping (threshold: {outlier_threshold}) and missing value imputation (strategy: {imputation_strategy})."
        ])

        if mode == "clean":
            imputation_and_outlier_code = [
                "# Impute missing values",
                "categorical_cols = [col for col in df.columns if not pd.api.types.is_numeric_dtype(df[col])]",
                "numeric_cols = [col for col in df.columns if pd.api.types.is_numeric_dtype(df[col])]",
                f"imputation_strategy = '{imputation_strategy}'",
                "",
                "for col in numeric_cols:",
                "    if df[col].isnull().any():",
                "        imputed_val = df[col].mean() if imputation_strategy == 'mean' else df[col].median()",
                "        if pd.isnull(imputed_val):",
                "            imputed_val = 0.0",
                "        df[col] = df[col].fillna(imputed_val)",
                "",
                "for col in categorical_cols:",
                "    if df[col].isnull().any():",
                "        mode_series = df[col].mode()",
                "        mode_val = mode_series.iloc[0] if not mode_series.empty else 'Unknown'",
                "        df[col] = df[col].fillna(mode_val)"
            ]
            if outlier_threshold != "None":
                outlier_code = [
                    "",
                    "# Outlier clipping",
                    f"target_column = '{target_column}'",
                    f"outlier_threshold = {outlier_threshold}",
                    "for col in numeric_cols:",
                    "    if col != target_column:",
                    "        mean_val = df[col].mean()",
                    "        std_val = df[col].std(ddof=0)",
                    "        if std_val > 0:",
                    "            df[col] = df[col].clip(mean_val - outlier_threshold * std_val, mean_val + outlier_threshold * std_val)"
                ]
                imputation_and_outlier_code.extend(outlier_code)
            add_code(imputation_and_outlier_code)
        else:
            add_code([
                "print('Missing Values Before Preprocessing:')",
                "print(df.isnull().sum())",
                "",
                "categorical_cols = [col for col in df.columns if not pd.api.types.is_numeric_dtype(df[col])]",
                "numeric_cols = [col for col in df.columns if pd.api.types.is_numeric_dtype(df[col])]",
                f"target_column = '{target_column}'",
                f"imputation_strategy = '{imputation_strategy}'",
                f"outlier_threshold = {outlier_threshold}",
                "",
                "# 1. Outlier Clipping",
                "if outlier_threshold is not None:",
                "    print(f'\\nClipping outliers beyond {outlier_threshold} standard deviations...')",
                "    for col in numeric_cols:",
                "        if col != target_column:",
                "            mean_val = df[col].mean()",
                "            std_val = df[col].std(ddof=0)",
                "            if std_val > 0:",
                "                lower_bound = mean_val - outlier_threshold * std_val",
                "                upper_bound = mean_val + outlier_threshold * std_val",
                "                df[col] = df[col].clip(lower_bound, upper_bound)",
                "",
                "# 2. Impute Numeric Features",
                "for col in numeric_cols:",
                "    if df[col].isnull().any():",
                "        if imputation_strategy == 'mean':",
                "            imputed_val = df[col].mean()",
                "        else:",
                "            imputed_val = df[col].median()",
                "        if pd.isnull(imputed_val):",
                "            imputed_val = 0.0",
                "        df[col] = df[col].fillna(imputed_val)",
                "        print(f\"Imputed numeric column '{col}' with {imputation_strategy}: {imputed_val}\")",
                "",
                "# 3. Impute Categorical Features",
                "for col in categorical_cols:",
                "    if df[col].isnull().any():",
                "        mode_series = df[col].mode()",
                "        mode_val = mode_series.iloc[0] if not mode_series.empty else 'Unknown'",
                "        df[col] = df[col].fillna(mode_val)",
                "        print(f\"Imputed categorical column '{col}' with mode: {mode_val}\")",
                "",
                "print('\\nMissing Values After Preprocessing:')",
                "print(df.isnull().sum())"
            ])

        # Section 4: Feature Engineering
        add_markdown([
            "## Section 4: Feature Engineering",
            "Maps categorical labels using `LabelEncoder` and normalizes features using `StandardScaler` (population standard deviation)."
        ])

        if mode == "clean":
            add_code([
                "# Encode categoricals and scale features",
                "from sklearn.preprocessing import LabelEncoder",
                "",
                "processed_df = df.copy()",
                "label_encoders = {}",
                "",
                "for col in categorical_cols:",
                "    le = LabelEncoder()",
                "    processed_df[col] = le.fit_transform(processed_df[col].astype(str))",
                "    label_encoders[col] = le",
                "",
                f"scaled_cols = [col for col in processed_df.columns if pd.api.types.is_numeric_dtype(processed_df[col]) and col != '{target_column}']",
                "for col in scaled_cols:",
                "    mean_val = processed_df[col].mean()",
                "    std_val = processed_df[col].std(ddof=0)",
                "    if std_val > 0:",
                "        processed_df[col] = (processed_df[col] - mean_val) / std_val",
                "    else:",
                "        processed_df[col] = 0.0"
            ])
        else:
            add_code([
                "from sklearn.preprocessing import LabelEncoder",
                "",
                "processed_df = df.copy()",
                "label_encoders = {}",
                "",
                "# 1. Label Encoding",
                "for col in categorical_cols:",
                "    le = LabelEncoder()",
                "    processed_df[col] = le.fit_transform(processed_df[col].astype(str))",
                "    label_encoders[col] = le",
                "    print(f\"Encoded categorical feature '{col}' using LabelEncoder\")",
                "",
                "# 2. Standard Scaling",
                f"scaled_cols = [col for col in processed_df.columns if pd.api.types.is_numeric_dtype(processed_df[col]) and col != '{target_column}']",
                "for col in scaled_cols:",
                "    mean_val = processed_df[col].mean()",
                "    std_val = processed_df[col].std(ddof=0)",
                "    if std_val > 0:",
                "        processed_df[col] = (processed_df[col] - mean_val) / std_val",
                "        print(f\"Normalized feature '{col}' (mean={mean_val:.4f}, std={std_val:.4f})\")",
                "    else:",
                "        processed_df[col] = 0.0",
                "        print(f\"Zeroed constant feature '{col}'\")",
                "",
                "print('\\n--- Processed DataFrame Head ---')",
                "display(processed_df.head())"
            ])

        # Section 5: EDA Visualizations
        add_markdown([
            "## Section 5: EDA Visualizations",
            "Renders histograms, correlation heatmaps, missing value counts, and outlier boxplots."
        ])

        if mode == "clean":
            add_code([
                "# EDA Plots",
                "import matplotlib.pyplot as plt",
                "import seaborn as sns",
                "",
                "sns.set_theme(style='darkgrid')",
                "plt.rcParams['figure.figsize'] = (10, 6)",
                "",
                "numeric_cols_for_plot = [col for col in df.columns if pd.api.types.is_numeric_dtype(df[col])]",
                "num_features = len(numeric_cols_for_plot)",
                "if num_features > 0:",
                "    cols = 2",
                "    rows = (num_features + 1) // 2",
                "    fig, axes = plt.subplots(rows, cols, figsize=(14, rows * 3))",
                "    if num_features == 1:",
                "        sns.histplot(df[numeric_cols_for_plot[0]], kde=True, ax=axes)",
                "        axes.set_title(f'Distribution of {numeric_cols_for_plot[0]}')",
                "    else:",
                "        axes = axes.flatten()",
                "        for idx, col in enumerate(numeric_cols_for_plot):",
                "            sns.histplot(df[col], kde=True, ax=axes[idx])",
                "            axes[idx].set_title(f'Distribution of {col}')",
                "        for i in range(num_features, len(axes)):",
                "            fig.delaxes(axes[i])",
                "    plt.tight_layout()",
                "    plt.show()",
                "",
                "plt.figure(figsize=(10, 8))",
                "sns.heatmap(processed_df.corr(), annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)",
                "plt.title('Correlation Heatmap')",
                "plt.show()",
                "",
                "if len(scaled_cols) > 0:",
                "    fig, axes = plt.subplots((len(scaled_cols) + 1) // 2, 2, figsize=(14, len(scaled_cols) * 1.8))",
                "    if len(scaled_cols) == 1:",
                "        sns.boxplot(y=df[scaled_cols[0]], ax=axes)",
                "        axes.set_title(f'Boxplot of {scaled_cols[0]}')",
                "    else:",
                "        axes = axes.flatten()",
                "        for idx, col in enumerate(scaled_cols):",
                "            sns.boxplot(y=df[col], ax=axes[idx])",
                "            axes[idx].set_title(f'Boxplot of {col}')",
                "        for i in range(len(scaled_cols), len(axes)):",
                "            fig.delaxes(axes[i])",
                "    plt.tight_layout()",
                "    plt.show()"
            ])
        else:
            add_code([
                "import matplotlib.pyplot as plt",
                "import seaborn as sns",
                "",
                "sns.set_theme(style='darkgrid')",
                "plt.rcParams['figure.figsize'] = (10, 6)",
                "",
                "# 1. Feature Distributions",
                "numeric_cols_for_plot = [col for col in df.columns if pd.api.types.is_numeric_dtype(df[col])]",
                "num_features = len(numeric_cols_for_plot)",
                "if num_features > 0:",
                "    print('Plotting feature distribution histograms...')",
                "    cols = 2",
                "    rows = (num_features + 1) // 2",
                "    fig, axes = plt.subplots(rows, cols, figsize=(14, rows * 3))",
                "    if num_features == 1:",
                "        sns.histplot(df[numeric_cols_for_plot[0]], kde=True, ax=axes)",
                "        axes.set_title(f'Distribution of {numeric_cols_for_plot[0]}')",
                "    else:",
                "        axes = axes.flatten()",
                "        for idx, col in enumerate(numeric_cols_for_plot):",
                "            sns.histplot(df[col], kde=True, ax=axes[idx])",
                "            axes[idx].set_title(f'Distribution of {col}')",
                "        for i in range(num_features, len(axes)):",
                "            fig.delaxes(axes[i])",
                "    plt.tight_layout()",
                "    plt.show()",
                "",
                "# 2. Correlation Heatmap",
                "print('Plotting correlation heatmap matrix...')",
                "plt.figure(figsize=(10, 8))",
                "sns.heatmap(processed_df.corr(), annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5)",
                "plt.title('Correlation Heatmap')",
                "plt.show()",
                "",
                "# 3. Outlier Boxplots",
                "if len(scaled_cols) > 0:",
                "    print('Plotting outlier boxplots...')",
                "    fig, axes = plt.subplots((len(scaled_cols) + 1) // 2, 2, figsize=(14, len(scaled_cols) * 1.8))",
                "    if len(scaled_cols) == 1:",
                "        sns.boxplot(y=df[scaled_cols[0]], ax=axes)",
                "        axes.set_title(f'Boxplot of {scaled_cols[0]}')",
                "    else:",
                "        axes = axes.flatten()",
                "        for idx, col in enumerate(scaled_cols):",
                "            sns.boxplot(y=df[col], ax=axes[idx])",
                "            axes[idx].set_title(f'Boxplot of {col}')",
                "        for i in range(len(scaled_cols), len(axes)):",
                "            fig.delaxes(axes[i])",
                "    plt.tight_layout()",
                "    plt.show()"
            ])

        # Section 6: Problem Detection (Only in Learning Mode)
        add_markdown([
            "## Section 6: Problem Detection",
            f"Identified problem properties on dataset target label `{target_column}`."
        ])
        if mode == "learning":
            add_code([
                f"print(\"Detected Target Column: '{target_column}'\")",
                f"print(\"Detected Problem Type:  '{problem_type}'\")",
                f"print(\"Classification Type:    '{classification_type}'\")",
                f"print(\"Number of Classes:      {num_classes}\")"
            ])

        # Section 7: Model Selection (Only in Learning Mode)
        add_markdown([
            "## Section 7: Model Selection & Design Heuristics",
            f"Recommends algorithms optimized for **{problem_type}**.",
            "- Classification: Logistic Regression, Random Forest Classifier, Decision Tree Classifier.",
            "- Regression: Linear Regression, Random Forest Regressor, Decision Tree Regressor."
        ])

        # Section 8 & 9: Model Training & Evaluation
        add_markdown([
            "## Section 8 & 9: Model Training and Evaluation",
            "Splits features and target variables into Train/Test splits, trains candidate estimators, and runs validation metrics."
        ])

        if mode == "clean":
            training_code = [
                "# Split data and train models",
                "from sklearn.model_selection import train_test_split",
                "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix",
                "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score",
                "import numpy as np",
                "",
                f"features = processed_df.drop(columns=['{target_column}'])",
                f"target = processed_df['{target_column}']",
                "",
                f"train_features, test_features, train_target, test_target = train_test_split(features, target, train_size={split_ratio}, random_state=42)",
                "",
                "models = {}",
                "results = {}",
                ""
            ]

            if problem_type == "Classification":
                training_code.extend([
                    "from sklearn.linear_model import LogisticRegression",
                    "from sklearn.ensemble import RandomForestClassifier",
                    "from sklearn.tree import DecisionTreeClassifier",
                    "",
                    "candidate_models = {",
                    "    'LogisticRegression': LogisticRegression(random_state=42, max_iter=1000),",
                    "    'RandomForestClassifier': RandomForestClassifier(random_state=42),",
                    "    'DecisionTreeClassifier': DecisionTreeClassifier(random_state=42)",
                    "}",
                    f"selected_models = {selected_models_str}",
                    "if selected_models:",
                    "    models = {k: v for k, v in candidate_models.items() if k in selected_models}",
                    "else:",
                    "    models = candidate_models",
                    "",
                    "for name, model in models.items():",
                    "    model.fit(train_features, train_target)",
                    "    predictions = model.predict(test_features)",
                    "    ",
                    "    acc = accuracy_score(test_target, predictions)",
                    "    prec = precision_score(test_target, predictions, average='weighted', zero_division=0)",
                    "    rec = recall_score(test_target, predictions, average='weighted', zero_division=0)",
                    "    f1 = f1_score(test_target, predictions, average='weighted', zero_division=0)",
                    "    cm = confusion_matrix(test_target, predictions)",
                    "    ",
                    "    results[name] = {",
                    "        'Accuracy': acc,",
                    "        'Precision': prec,",
                    "        'Recall': rec,",
                    "        'F1 Score': f1,",
                    "        'Confusion Matrix': cm",
                    "    }",
                    "    print(f'[{name}] Accuracy: {acc:.4f} | F1: {f1:.4f}')"
                ])
            else:
                training_code.extend([
                    "from sklearn.linear_model import LinearRegression",
                    "from sklearn.ensemble import RandomForestRegressor",
                    "from sklearn.tree import DecisionTreeRegressor",
                    "",
                    "candidate_models = {",
                    "    'LinearRegression': LinearRegression(),",
                    "    'RandomForestRegressor': RandomForestRegressor(random_state=42),",
                    "    'DecisionTreeRegressor': DecisionTreeRegressor(random_state=42)",
                    "}",
                    f"selected_models = {selected_models_str}",
                    "if selected_models:",
                    "    models = {k: v for k, v in candidate_models.items() if k in selected_models}",
                    "else:",
                    "    models = candidate_models",
                    "",
                    "for name, model in models.items():",
                    "    model.fit(train_features, train_target)",
                    "    predictions = model.predict(test_features)",
                    "    ",
                    "    mae = mean_absolute_error(test_target, predictions)",
                    "    rmse = np.sqrt(mean_squared_error(test_target, predictions))",
                    "    r2 = r2_score(test_target, predictions)",
                    "    ",
                    "    results[name] = {",
                    "        'MAE': mae,",
                    "        'RMSE': rmse,",
                    "        'R2 Score': r2",
                    "    }",
                    "    print(f'[{name}] R2: {r2:.4f} | RMSE: {rmse:.4f}')"
                ])
            add_code(training_code)
        else:
            training_code = [
                "from sklearn.model_selection import train_test_split",
                "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix",
                "from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score",
                "import numpy as np",
                "",
                "# 1. Features & Target Split",
                f"X = processed_df.drop(columns=['{target_column}'])",
                f"y = processed_df['{target_column}']",
                "",
                f"X_train, X_test, y_train, y_test = train_test_split(X, y, train_size={split_ratio}, random_state=42)",
                "print(f'Train split size: {X_train.shape[0]} rows')",
                "print(f'Test split size:  {X_test.shape[0]} rows')",
                "",
                "# 2. Training loop",
                "models = {}",
                "results = {}",
                ""
            ]

            if problem_type == "Classification":
                training_code.extend([
                    "from sklearn.linear_model import LogisticRegression",
                    "from sklearn.ensemble import RandomForestClassifier",
                    "from sklearn.tree import DecisionTreeClassifier",
                    "",
                    "candidate_models = {",
                    "    'LogisticRegression': LogisticRegression(random_state=42, max_iter=1000),",
                    "    'RandomForestClassifier': RandomForestClassifier(random_state=42),",
                    "    'DecisionTreeClassifier': DecisionTreeClassifier(random_state=42)",
                    "}",
                    f"selected_models = {selected_models_str}",
                    "if selected_models:",
                    "    models = {k: v for k, v in candidate_models.items() if k in selected_models}",
                    "else:",
                    "    models = candidate_models",
                    "",
                    "for name, model in models.items():",
                    "    print(f'\\nTraining model: {name}...')",
                    "    model.fit(X_train, y_train)",
                    "    y_pred = model.predict(X_test)",
                    "    ",
                    "    acc = accuracy_score(y_test, y_pred)",
                    "    prec = precision_score(y_test, y_pred, average='weighted', zero_division=0)",
                    "    rec = recall_score(y_test, y_pred, average='weighted', zero_division=0)",
                    "    f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)",
                    "    cm = confusion_matrix(y_test, y_pred)",
                    "    ",
                    "    results[name] = {",
                    "        'Accuracy': acc,",
                    "        'Precision': prec,",
                    "        'Recall': rec,",
                    "        'F1 Score': f1,",
                    "        'Confusion Matrix': cm",
                    "    }",
                    "    ",
                    "    print(f'[{name}] Metrics:')",
                    "    print(f'  Accuracy:  {acc:.4f}')",
                    "    print(f'  Precision: {prec:.4f}')",
                    "    print(f'  Recall:    {rec:.4f}')",
                    "    print(f'  F1 Score:  {f1:.4f}')",
                    "    ",
                    "    # Plot Confusion Matrix",
                    "    plt.figure(figsize=(5, 4))",
                    "    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')",
                    "    plt.title(f'Confusion Matrix - {name}')",
                    "    plt.ylabel('Actual')",
                    "    plt.xlabel('Predicted')",
                    "    plt.show()"
                ])
            else:
                training_code.extend([
                    "from sklearn.linear_model import LinearRegression",
                    "from sklearn.ensemble import RandomForestRegressor",
                    "from sklearn.tree import DecisionTreeRegressor",
                    "",
                    "candidate_models = {",
                    "    'LinearRegression': LinearRegression(),",
                    "    'RandomForestRegressor': RandomForestRegressor(random_state=42),",
                    "    'DecisionTreeRegressor': DecisionTreeRegressor(random_state=42)",
                    "}",
                    f"selected_models = {selected_models_str}",
                    "if selected_models:",
                    "    models = {k: v for k, v in candidate_models.items() if k in selected_models}",
                    "else:",
                    "    models = candidate_models",
                    "",
                    "for name, model in models.items():",
                    "    print(f'\\nTraining model: {name}...')",
                    "    model.fit(X_train, y_train)",
                    "    y_pred = model.predict(X_test)",
                    "    ",
                    "    mae = mean_absolute_error(y_test, y_pred)",
                    "    rmse = np.sqrt(mean_squared_error(y_test, y_pred))",
                    "    r2 = r2_score(y_test, y_pred)",
                    "    ",
                    "    results[name] = {",
                    "        'MAE': mae,",
                    "        'RMSE': rmse,",
                    "        'R2 Score': r2",
                    "    }",
                    "    ",
                    "    print(f'[{name}] Metrics:')",
                    "    print(f'  MAE:      {mae:.4f}')",
                    "    print(f'  RMSE:     {rmse:.4f}')",
                    "    print(f'  R2 Score: {r2:.4f}')",
                    "    ",
                    "    # Plot actual vs predicted scatter",
                    "    plt.figure(figsize=(6, 5))",
                    "    plt.scatter(y_test, y_pred, alpha=0.5)",
                    "    plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)",
                    "    plt.title(f'Actual vs Predicted - {name}')",
                    "    plt.xlabel('Actual')",
                    "    plt.ylabel('Predicted')",
                    "    plt.show()"
                ])
            add_code(training_code)

        # Section 10: Feature Importance
        add_markdown([
            "## Section 10: Feature Importance",
            "Plots variable importances computed by fitted Random Forest or Decision Tree estimators."
        ])

        if mode == "clean":
            add_code([
                "# Feature importance",
                "for name, model in models.items():",
                "    if hasattr(model, 'feature_importances_'):",
                "        importances = model.feature_importances_",
                "        indices = np.argsort(importances)[::-1]",
                "        features_names = features.columns",
                "        ",
                "        plt.figure(figsize=(10, 6))",
                "        sns.barplot(x=importances[indices], y=features_names[indices])",
                "        plt.title(f'Feature Importances - {name}')",
                "        plt.show()"
            ])
        else:
            add_code([
                "print('Computing feature importances...\\n')",
                "for name, model in models.items():",
                "    if hasattr(model, 'feature_importances_'):",
                "        importances = model.feature_importances_",
                "        indices = np.argsort(importances)[::-1]",
                "        features = X.columns",
                "        ",
                "        plt.figure(figsize=(10, 6))",
                "        sns.barplot(x=importances[indices], y=features[indices])",
                "        plt.title(f'Feature Importances - {name}')",
                "        plt.xlabel('Importance Weight')",
                "        plt.ylabel('Features')",
                "        plt.show()",
                "        ",
                "        print(f'Top 5 Features for {name}:')",
                "        for f_idx in indices[:5]:",
                "            print(f'  {features[f_idx]}: {importances[f_idx]:.4f}')"
            ])

        # Section 11: Prediction Pipeline
        add_markdown([
            "## Section 11: Prediction Pipeline",
            "Executes a prediction sample on selected records from the testing set, demonstrating raw and label-decoded predictions."
        ])

        if mode == "clean":
            add_code([
                "# Test prediction on sample data",
                "sample_features = test_features.head(3)",
                "display(sample_features)",
                "",
                "for name, model in models.items():",
                "    predictions = model.predict(sample_features)",
                "    print(f'Predictions using {name}: {predictions}')",
                f"    if '{problem_type}' == 'Classification' and '{target_column}' in label_encoders:",
                f"        decoded = label_encoders['{target_column}'].inverse_transform(predictions)",
                "        print(f'Decoded: {decoded}')"
            ])
        else:
            add_code([
                "sample_X = X_test.head(3)",
                "print('Testing prediction workflow on sample test inputs:')",
                "display(sample_X)",
                "",
                "for name, model in models.items():",
                "    preds = model.predict(sample_X)",
                "    print(f'\\nPredictions using {name}:')",
                f"    if '{problem_type}' == 'Classification' and '{target_column}' in label_encoders:",
                f"        decoded = label_encoders['{target_column}'].inverse_transform(preds)",
                "        print(f'  Raw Output: {preds} -> Decoded Class: {decoded}')",
                "    else:",
                "        print(f'  Output: {preds}')"
            ])

        # Section 12: Conclusion (Only in Learning Mode)
        add_markdown([
            "## Section 12: Conclusion",
            "The pipelines executed above match the configuration, preprocessing, and training stages completed in the ADSA platform.",
            "",
            "### Future Expansion Architectures",
            "This export service is designed to support modular targets. In future updates, this code template can be transformed into:",
            "- **Kaggle Notebooks** integration",
            "- **Streamlit Applications** dashboard",
            "- **FastAPI & Flask APIs** prediction backends",
            "- **Dockerized** microservices"
        ])

        # Construct full Notebook
        notebook = {
            "cells": cells,
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3 (ipykernel)",
                    "language": "python",
                    "name": "python3"
                },
                "language_info": {
                    "name": "python"
                }
            },
            "nbformat": 4,
            "nbformat_minor": 2
        }

        return notebook

    @staticmethod
    def generate_python_script(dataset_id: str, mode: str = "clean", user_id=None) -> str:
        notebook = NotebookGeneratorService.generate_notebook_dict(dataset_id, mode=mode, user_id=user_id)
        script_parts = []
        for cell in notebook["cells"]:
            if cell["cell_type"] == "markdown":
                script_parts.append("# " + "="*60)
                for line in cell["source"]:
                    cleaned_line = line.rstrip("\n")
                    script_parts.append(f"# {cleaned_line}")
                script_parts.append("# " + "="*60 + "\n")
            elif cell["cell_type"] == "code":
                for line in cell["source"]:
                    script_parts.append(line.rstrip("\n"))
                script_parts.append("\n")
        return "\n".join(script_parts)

    @staticmethod
    def upload_to_gist(dataset_id: str, github_token: str, mode: str = "clean", user_id=None) -> str:
        import requests
        
        # 1. Generate notebook content
        notebook = NotebookGeneratorService.generate_notebook_dict(dataset_id, mode=mode, user_id=user_id)
        notebook_str = json.dumps(notebook, indent=2)
        
        # 2. Get dataset details
        dataset = DatasetService.get_dataset_by_id(dataset_id, user_id=user_id)
        filename = dataset.get("filename", "dataset.csv")
        gist_filename = filename.rsplit(".", 1)[0] + "_ADSA_Workflow.ipynb"
        
        # 3. Create Gist payload
        payload = {
            "description": f"ADSA Machine Learning Workflow Pipeline for {filename} ({mode.capitalize()} Mode)",
            "public": True,
            "files": {
                gist_filename: {
                    "content": notebook_str
                }
            }
        }
        
        headers = {
            "Authorization": f"token {github_token}",
            "Accept": "application/vnd.github.v3+json"
        }
        
        response = requests.post("https://api.github.com/gists", json=payload, headers=headers)
        if response.status_code != 201:
            raise Exception(f"GitHub API Error: {response.text}")
            
        gist_data = response.json()
        gist_id = gist_data.get("id")
        owner = gist_data.get("owner", {}).get("login", "anonymous")
        
        # 4. Return Colab Gist URL
        colab_url = f"https://colab.research.google.com/gist/{owner}/{gist_id}/{gist_filename}"
        return colab_url
