export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#fffaf4",
        "surface-bright": "#3a3939",
        "on-background": "#e5e2e1",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#002021",
        "on-secondary-fixed-variant": "#474646",
        "primary-fixed": "#ffe251",
        "secondary": "#c8c6c5",
        "on-tertiary-container": "#006d70",
        "on-secondary": "#313030",
        "primary-container": "#ffdd00",
        "surface-container-highest": "#353534",
        "on-primary-fixed-variant": "#524600",
        "surface-tint": "#e4c600",
        "surface-card": "#171717",
        "on-secondary-fixed": "#1c1b1b",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#00f6fd",
        "surface-container-lowest": "#0e0e0e",
        "outline": "#989177",
        "surface-variant": "#353534",
        "on-tertiary": "#003738",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary": "#eaffff",
        "text-secondary": "#A1A1AA",
        "background": "#0A0A0A",
        "primary-fixed-dim": "#e4c600",
        "tertiary-fixed": "#4bf9ff",
        "outline-variant": "#4c4732",
        "on-surface": "#e5e2e1",
        "surface-container": "#201f1f",
        "secondary-container": "#4a4949",
        "border-subtle": "#2A2A2A",
        "on-primary": "#393000",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#cfc6ab",
        "on-secondary-container": "#bab8b7",
        "surface-dim": "#131313",
        "inverse-surface": "#e5e2e1",
        "on-error": "#690005",
        "on-primary-container": "#716100",
        "surface-container-low": "#1c1b1b",
        "error-container": "#93000a",
        "inverse-primary": "#6d5e00",
        "accent-hover": "#FFD000",
        "on-tertiary-fixed-variant": "#004f52",
        "text-primary": "#FFFFFF",
        "on-primary-fixed": "#211b00",
        "inverse-on-surface": "#313030",
        "surface": "#131313",
        "tertiary-fixed-dim": "#00dce2",
        "error": "#ffb4ab"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "container-max": "1440px",
        "gutter": "24px",
        "margin-tablet": "32px",
        "baseline": "4px"
      },
      fontFamily: {
        "display-lg": ["DM Sans"],
        "code-snippet": ["DM Mono"],
        "display-lg-mobile": ["DM Sans"],
        "label-md": ["Inter"],
        "headline-sm": ["DM Sans"],
        "body-md": ["Inter"],
        "headline-md": ["DM Sans"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "code-snippet": ["14px", {"lineHeight": "22px", "fontWeight": "400"}],
        "display-lg-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
